INTERNAL_WIDTH = 320
INTERNAL_HEIGHT = 180
INTERNAL_SIZE = (INTERNAL_WIDTH, INTERNAL_HEIGHT)

BORDER_WIDTH = 35
PLAYABLE_X = BORDER_WIDTH
PLAYABLE_WIDTH = 250
PLAYABLE_RIGHT = PLAYABLE_X + PLAYABLE_WIDTH

CHUNK_HEIGHT = INTERNAL_HEIGHT

PLAYER_FRAME_WIDTH = 24
PLAYER_FRAME_HEIGHT = 32
PLAYER_FRAME_SIZE = (PLAYER_FRAME_WIDTH, PLAYER_FRAME_HEIGHT)
PLAYER_HITBOX_WIDTH = 16
PLAYER_HITBOX_HEIGHT = 28
PLAYER_HITBOX_SIZE = (PLAYER_HITBOX_WIDTH, PLAYER_HITBOX_HEIGHT)

PLATFORM_NORMAL_WIDTH = 64
PLATFORM_NORMAL_HEIGHT = 8
PLATFORM_NORMAL_SIZE = (PLATFORM_NORMAL_WIDTH, PLATFORM_NORMAL_HEIGHT)
