INTERNAL_WIDTH = 320
INTERNAL_HEIGHT = 180
INTERNAL_SIZE = (INTERNAL_WIDTH, INTERNAL_HEIGHT)

BORDER_WIDTH = 35
PLAYABLE_X = BORDER_WIDTH
PLAYABLE_WIDTH = 250
PLAYABLE_RIGHT = PLAYABLE_X + PLAYABLE_WIDTH

CHUNK_HEIGHT = INTERNAL_HEIGHT

PLAYER_FRAME_WIDTH = 24
PLAYER_FRAME_HEIGHT = 32
PLAYER_FRAME_SIZE = (PLAYER_FRAME_WIDTH, PLAYER_FRAME_HEIGHT)
PLAYER_HITBOX_WIDTH = 16
PLAYER_HITBOX_HEIGHT = 28
PLAYER_HITBOX_SIZE = (PLAYER_HITBOX_WIDTH, PLAYER_HITBOX_HEIGHT)

PLATFORM_NORMAL_WIDTH = 64
PLATFORM_NORMAL_HEIGHT = 8
PLATFORM_NORMAL_SIZE = (PLATFORM_NORMAL_WIDTH, PLATFORM_NORMAL_HEIGHT)
PLATFORM_WIDTH_OPTIONS = (32, 40, 48, 65, 96)

PLAYER_MOVE_SPEED = 90.0
PLAYER_GRAVITY = 520.0
PLAYER_JUMP_VELOCITY = -220.0
PLAYER_NORMAL_JUMP_HEIGHT = (abs(PLAYER_JUMP_VELOCITY) ** 2) / (2 * PLAYER_GRAVITY)
PLAYER_PLATFORM_CLEARANCE_MARGIN = 4
PLAYER_MIN_PLATFORM_VERTICAL_GAP = PLAYER_HITBOX_HEIGHT + PLATFORM_NORMAL_HEIGHT + PLAYER_PLATFORM_CLEARANCE_MARGIN
PLAYER_PLATFORM_GAP_SAFETY_MARGIN = 4.0
PLAYER_MAX_NORMAL_JUMP_PLATFORM_GAP = int(PLAYER_NORMAL_JUMP_HEIGHT - PLAYER_PLATFORM_GAP_SAFETY_MARGIN)
PLAYER_PLATFORM_SIDE_CLEARANCE = PLAYER_HITBOX_WIDTH + 6
