-- 001_init.sql — initial schema (users + refresh tokens).
--
-- Loaded by Postgres on first container init via the docker-entrypoint-initdb.d
-- mount in docker-compose.yml. To re-run: `docker-compose down -v && docker-compose up -d`.
--
-- When we add more migrations, swap this single-file approach for golang-migrate
-- or goose. For now (one file), plain init is simpler.

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id text PRIMARY KEY,                              -- ULID, generated by server
    email text NOT NULL UNIQUE,                       -- canonical lowercased on insert
    display_name text NOT NULL UNIQUE,                -- globally unique (vault decision)
    password_hash text NOT NULL,                      -- bcrypt
    verified boolean NOT NULL DEFAULT false,
    verification_token text,                          -- one-time, NULL after use/expiry
    verification_token_expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Case-insensitive email lookup
CREATE INDEX IF NOT EXISTS users_email_lower_idx ON users (lower(email));

-- Case-insensitive display_name lookup (when validating uniqueness on register)
CREATE INDEX IF NOT EXISTS users_display_name_lower_idx ON users (lower(display_name));

-- ---------------------------------------------------------------------------
-- refresh_tokens
-- ---------------------------------------------------------------------------
-- Stores HASHED refresh tokens (sha256), never plaintext. On /auth/refresh
-- the server hashes the incoming token and looks up by hash. On /auth/logout
-- we set revoked_at. Expired/revoked rows are tombstones for audit; a future
-- cron can prune > 90 days past expires_at.
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id text PRIMARY KEY,                              -- ULID
    user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,                  -- sha256(refresh_token), hex
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz
);

CREATE INDEX IF NOT EXISTS refresh_tokens_user_id_idx ON refresh_tokens (user_id);

-- Partial index over still-active tokens — the common lookup on /auth/refresh.
CREATE INDEX IF NOT EXISTS refresh_tokens_active_idx
    ON refresh_tokens (token_hash)
    WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_touch_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION touch_updated_at();
